# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from evidencelens.v1 import scorer_pb2 as evidencelens_dot_v1_dot_scorer__pb2


class ScorerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_stream(
                '/evidencelens.v1.ScorerService/Search',
                request_serializer=evidencelens_dot_v1_dot_scorer__pb2.SearchRequest.SerializeToString,
                response_deserializer=evidencelens_dot_v1_dot_scorer__pb2.PartialResults.FromString,
                _registered_method=True)
        self.Healthz = channel.unary_unary(
                '/evidencelens.v1.ScorerService/Healthz',
                request_serializer=evidencelens_dot_v1_dot_scorer__pb2.ScorerHealthzRequest.SerializeToString,
                response_deserializer=evidencelens_dot_v1_dot_scorer__pb2.ScorerHealthzResponse.FromString,
                _registered_method=True)


class ScorerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """Server-streaming search. The server emits multiple PartialResults
        messages over the lifetime of a single request, each refining the
        ranking with more sub-scorer signals. Clients should render each wave
        immediately and replace prior content.
        
        Deadline propagation: the gateway sets `grpc-timeout` (e.g. 800m).
        The scorer subdivides budget across sub-scorers and emits whatever it
        has when the deadline expires.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Healthz(self, request, context):
        """Synchronous health probe used by docker-compose / Kubernetes / OTel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScorerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_stream_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=evidencelens_dot_v1_dot_scorer__pb2.SearchRequest.FromString,
                    response_serializer=evidencelens_dot_v1_dot_scorer__pb2.PartialResults.SerializeToString,
            ),
            'Healthz': grpc.unary_unary_rpc_method_handler(
                    servicer.Healthz,
                    request_deserializer=evidencelens_dot_v1_dot_scorer__pb2.ScorerHealthzRequest.FromString,
                    response_serializer=evidencelens_dot_v1_dot_scorer__pb2.ScorerHealthzResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evidencelens.v1.ScorerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('evidencelens.v1.ScorerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScorerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/evidencelens.v1.ScorerService/Search',
            evidencelens_dot_v1_dot_scorer__pb2.SearchRequest.SerializeToString,
            evidencelens_dot_v1_dot_scorer__pb2.PartialResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Healthz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evidencelens.v1.ScorerService/Healthz',
            evidencelens_dot_v1_dot_scorer__pb2.ScorerHealthzRequest.SerializeToString,
            evidencelens_dot_v1_dot_scorer__pb2.ScorerHealthzResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
