// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: evidencelens/v1/document.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "evidencelens.v1";

/**
 * Coarse classification of evidence type, used as an LTR feature and for
 * faceted search filtering. Values track those in spec §3.1.
 */
export enum StudyType {
  STUDY_TYPE_UNSPECIFIED = 0,
  RCT = 1,
  META_ANALYSIS = 2,
  SYSTEMATIC_REVIEW = 3,
  OBSERVATIONAL = 4,
  CASE_REPORT = 5,
  PREPRINT = 6,
  TRIAL_REGISTRY = 7,
  REGULATORY = 8,
  GUIDELINE = 9,
  REVIEW = 10,
  EDITORIAL = 11,
  OTHER = 99,
  UNRECOGNIZED = -1,
}

export function studyTypeFromJSON(object: any): StudyType {
  switch (object) {
    case 0:
    case "STUDY_TYPE_UNSPECIFIED":
      return StudyType.STUDY_TYPE_UNSPECIFIED;
    case 1:
    case "RCT":
      return StudyType.RCT;
    case 2:
    case "META_ANALYSIS":
      return StudyType.META_ANALYSIS;
    case 3:
    case "SYSTEMATIC_REVIEW":
      return StudyType.SYSTEMATIC_REVIEW;
    case 4:
    case "OBSERVATIONAL":
      return StudyType.OBSERVATIONAL;
    case 5:
    case "CASE_REPORT":
      return StudyType.CASE_REPORT;
    case 6:
    case "PREPRINT":
      return StudyType.PREPRINT;
    case 7:
    case "TRIAL_REGISTRY":
      return StudyType.TRIAL_REGISTRY;
    case 8:
    case "REGULATORY":
      return StudyType.REGULATORY;
    case 9:
    case "GUIDELINE":
      return StudyType.GUIDELINE;
    case 10:
    case "REVIEW":
      return StudyType.REVIEW;
    case 11:
    case "EDITORIAL":
      return StudyType.EDITORIAL;
    case 99:
    case "OTHER":
      return StudyType.OTHER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return StudyType.UNRECOGNIZED;
  }
}

export function studyTypeToJSON(object: StudyType): string {
  switch (object) {
    case StudyType.STUDY_TYPE_UNSPECIFIED:
      return "STUDY_TYPE_UNSPECIFIED";
    case StudyType.RCT:
      return "RCT";
    case StudyType.META_ANALYSIS:
      return "META_ANALYSIS";
    case StudyType.SYSTEMATIC_REVIEW:
      return "SYSTEMATIC_REVIEW";
    case StudyType.OBSERVATIONAL:
      return "OBSERVATIONAL";
    case StudyType.CASE_REPORT:
      return "CASE_REPORT";
    case StudyType.PREPRINT:
      return "PREPRINT";
    case StudyType.TRIAL_REGISTRY:
      return "TRIAL_REGISTRY";
    case StudyType.REGULATORY:
      return "REGULATORY";
    case StudyType.GUIDELINE:
      return "GUIDELINE";
    case StudyType.REVIEW:
      return "REVIEW";
    case StudyType.EDITORIAL:
      return "EDITORIAL";
    case StudyType.OTHER:
      return "OTHER";
    case StudyType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * A canonicalized biomedical evidence record. All ingesters produce these;
 * the processor enriches and the indexer fans out to Meilisearch / Milvus /
 * Neo4j.
 */
export interface Document {
  /**
   * Namespaced primary key. Examples: "pubmed:12345678",
   * "nct:NCT01234567", "fda-recall:F-2023-1234".
   */
  id: string;
  /**
   * Source corpus key. Examples: "pubmed", "biorxiv", "medrxiv", "ctgov",
   * "ictrp", "openfda-drug", "openfda-device", "openalex", "crossref",
   * "unpaywall", "nih-reporter", "open-payments", "cochrane", "guideline".
   */
  source: string;
  /** The source's native record id (PMID, DOI, NCT, FDA recall id, etc). */
  sourceNativeId: string;
  doi?: string | undefined;
  pmid?: string | undefined;
  pmcid?: string | undefined;
  nctId?: string | undefined;
  ictrpId?: string | undefined;
  title: string;
  abstract: string;
  /**
   * Populated only if the source license permits redistribution
   * (e.g. PMC OA Subset, CC-BY preprints). For closed-access content,
   * EvidenceLens stores metadata only and links out via canonical_url.
   */
  fullText?:
    | string
    | undefined;
  /** Deep link to the authoritative source page for the record. */
  canonicalUrl: string;
  ingestedAt: Date | undefined;
  sourceUpdatedAt: Date | undefined;
  publishedAt:
    | Date
    | undefined;
  /**
   * SPDX identifier (e.g. "CC-BY-4.0", "CC0-1.0") or verbatim license string
   * when no SPDX id is available (e.g. "U.S. Government work").
   */
  license: string;
  /**
   * Pointer into the object store (MinIO) raw archive at
   * `raw/{source}/{YYYY-MM-DD}/{id}.json.gz`. Used for reprocessing without
   * re-fetching from the upstream API.
   */
  objectRawKey: string;
  authors: Author[];
  studyType: StudyType;
  meshTerms: string[];
  keywords: string[];
  journal?: Journal | undefined;
  trial?: Trial | undefined;
  regulatory?:
    | Regulatory
    | undefined;
  /** Total inbound citation count from OpenAlex. */
  citationCount: number;
  /** PageRank computed by `page-rank` over the OpenAlex citation graph. */
  citationPagerank: number;
  /** Joined later from NIH RePORTER / NSF Awards / etc. */
  funding: FundingSource[];
  /**
   * 1024-d when produced by BGE-M3 (default) or 384-d when produced by
   * BGE-small-en-v1.5 (CPU fallback). The model identity is in
   * `embedding_model` so consumers can validate vector compatibility.
   */
  embedding: number[];
  embeddingModel: string;
}

/**
 * One author of a document. The `payments` field is populated by the
 * processor's author-payment-joiner (see spec §5.2 step 6).
 */
export interface Author {
  displayName: string;
  givenName?: string | undefined;
  familyName?: string | undefined;
  orcid?: string | undefined;
  affiliation?: string | undefined;
  payments: AuthorPayment[];
}

/**
 * One CMS Open Payments record matched to an author by the processor's
 * fuzzy joiner (rapidfuzz, default threshold 0.90). Conservative bias:
 * false positives are worse than false negatives. See
 * docs/sources/open-payments.md for matching policy.
 */
export interface AuthorPayment {
  sponsorName: string;
  year: string;
  amountUsd: number;
  /**
   * One of: "consulting", "honoraria", "research", "travel", "ownership",
   * "other".
   */
  paymentType: string;
  /** CMS Open Payments ID from the bulk CSV. */
  sourceRecordId: string;
}

/**
 * Journal metadata. `is_predatory` checks ISSN against a periodically
 * refreshed Beall's list snapshot.
 */
export interface Journal {
  name: string;
  issn?: string | undefined;
  publisher?: string | undefined;
  impactFactor?: number | undefined;
  isPredatory: boolean;
}

/**
 * Clinical trial registry record. Populated when the document originates in
 * ClinicalTrials.gov, WHO ICTRP, or another registry.
 */
export interface Trial {
  /** Registry identifier, e.g. "ctgov", "ictrp:eu-ctis", "ictrp:chictr". */
  registry: string;
  /**
   * One of: "recruiting", "active_not_recruiting", "completed",
   * "terminated", "suspended", "withdrawn", "unknown".
   */
  status: string;
  /**
   * One of: "early_phase_1", "phase_1", "phase_2", "phase_3", "phase_4",
   * "not_applicable".
   */
  phase: string;
  conditions: string[];
  interventions: string[];
  /** Free-form city / region / country strings as published by the registry. */
  locations: string[];
  enrollment?: number | undefined;
  startDate?: Date | undefined;
  completionDate?: Date | undefined;
  primaryOutcome?: string | undefined;
}

/**
 * Regulatory action record. Populated for openFDA, EMA, MHRA, Health
 * Canada, TGA, PMDA documents.
 */
export interface Regulatory {
  /** One of: "fda", "ema", "mhra", "health_canada", "tga", "pmda". */
  agency: string;
  /**
   * One of: "approval", "recall", "adverse_event", "510k_clearance",
   * "label_update".
   */
  eventType: string;
  productName: string;
  drugClass?:
    | string
    | undefined;
  /** For recalls, FDA classification: "I" (highest risk) | "II" | "III". */
  recallClass?: string | undefined;
  reason?: string | undefined;
  action?: string | undefined;
}

/**
 * One funding source for a document. Populated from NIH RePORTER, NSF
 * Awards, or similar. Multiple instances allowed per document.
 */
export interface FundingSource {
  /** Funder name, e.g. "NIH", "NSF", "Wellcome Trust". */
  funder: string;
  grantId?: string | undefined;
  amountUsd?: number | undefined;
  fiscalYear?: string | undefined;
}

function createBaseDocument(): Document {
  return {
    id: "",
    source: "",
    sourceNativeId: "",
    doi: undefined,
    pmid: undefined,
    pmcid: undefined,
    nctId: undefined,
    ictrpId: undefined,
    title: "",
    abstract: "",
    fullText: undefined,
    canonicalUrl: "",
    ingestedAt: undefined,
    sourceUpdatedAt: undefined,
    publishedAt: undefined,
    license: "",
    objectRawKey: "",
    authors: [],
    studyType: 0,
    meshTerms: [],
    keywords: [],
    journal: undefined,
    trial: undefined,
    regulatory: undefined,
    citationCount: 0,
    citationPagerank: 0,
    funding: [],
    embedding: [],
    embeddingModel: "",
  };
}

export const Document: MessageFns<Document> = {
  encode(message: Document, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.source !== "") {
      writer.uint32(18).string(message.source);
    }
    if (message.sourceNativeId !== "") {
      writer.uint32(26).string(message.sourceNativeId);
    }
    if (message.doi !== undefined) {
      writer.uint32(34).string(message.doi);
    }
    if (message.pmid !== undefined) {
      writer.uint32(42).string(message.pmid);
    }
    if (message.pmcid !== undefined) {
      writer.uint32(50).string(message.pmcid);
    }
    if (message.nctId !== undefined) {
      writer.uint32(58).string(message.nctId);
    }
    if (message.ictrpId !== undefined) {
      writer.uint32(66).string(message.ictrpId);
    }
    if (message.title !== "") {
      writer.uint32(82).string(message.title);
    }
    if (message.abstract !== "") {
      writer.uint32(90).string(message.abstract);
    }
    if (message.fullText !== undefined) {
      writer.uint32(98).string(message.fullText);
    }
    if (message.canonicalUrl !== "") {
      writer.uint32(106).string(message.canonicalUrl);
    }
    if (message.ingestedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.ingestedAt), writer.uint32(162).fork()).join();
    }
    if (message.sourceUpdatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.sourceUpdatedAt), writer.uint32(170).fork()).join();
    }
    if (message.publishedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.publishedAt), writer.uint32(178).fork()).join();
    }
    if (message.license !== "") {
      writer.uint32(186).string(message.license);
    }
    if (message.objectRawKey !== "") {
      writer.uint32(194).string(message.objectRawKey);
    }
    for (const v of message.authors) {
      Author.encode(v!, writer.uint32(242).fork()).join();
    }
    if (message.studyType !== 0) {
      writer.uint32(320).int32(message.studyType);
    }
    for (const v of message.meshTerms) {
      writer.uint32(330).string(v!);
    }
    for (const v of message.keywords) {
      writer.uint32(338).string(v!);
    }
    if (message.journal !== undefined) {
      Journal.encode(message.journal, writer.uint32(346).fork()).join();
    }
    if (message.trial !== undefined) {
      Trial.encode(message.trial, writer.uint32(354).fork()).join();
    }
    if (message.regulatory !== undefined) {
      Regulatory.encode(message.regulatory, writer.uint32(362).fork()).join();
    }
    if (message.citationCount !== 0) {
      writer.uint32(400).int64(message.citationCount);
    }
    if (message.citationPagerank !== 0) {
      writer.uint32(409).double(message.citationPagerank);
    }
    for (const v of message.funding) {
      FundingSource.encode(v!, writer.uint32(482).fork()).join();
    }
    writer.uint32(562).fork();
    for (const v of message.embedding) {
      writer.float(v);
    }
    writer.join();
    if (message.embeddingModel !== "") {
      writer.uint32(570).string(message.embeddingModel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Document {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDocument();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.source = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sourceNativeId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.doi = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.pmid = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.pmcid = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.nctId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.ictrpId = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.abstract = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.fullText = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.canonicalUrl = reader.string();
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.ingestedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.sourceUpdatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.publishedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.license = reader.string();
          continue;
        }
        case 24: {
          if (tag !== 194) {
            break;
          }

          message.objectRawKey = reader.string();
          continue;
        }
        case 30: {
          if (tag !== 242) {
            break;
          }

          message.authors.push(Author.decode(reader, reader.uint32()));
          continue;
        }
        case 40: {
          if (tag !== 320) {
            break;
          }

          message.studyType = reader.int32() as any;
          continue;
        }
        case 41: {
          if (tag !== 330) {
            break;
          }

          message.meshTerms.push(reader.string());
          continue;
        }
        case 42: {
          if (tag !== 338) {
            break;
          }

          message.keywords.push(reader.string());
          continue;
        }
        case 43: {
          if (tag !== 346) {
            break;
          }

          message.journal = Journal.decode(reader, reader.uint32());
          continue;
        }
        case 44: {
          if (tag !== 354) {
            break;
          }

          message.trial = Trial.decode(reader, reader.uint32());
          continue;
        }
        case 45: {
          if (tag !== 362) {
            break;
          }

          message.regulatory = Regulatory.decode(reader, reader.uint32());
          continue;
        }
        case 50: {
          if (tag !== 400) {
            break;
          }

          message.citationCount = longToNumber(reader.int64());
          continue;
        }
        case 51: {
          if (tag !== 409) {
            break;
          }

          message.citationPagerank = reader.double();
          continue;
        }
        case 60: {
          if (tag !== 482) {
            break;
          }

          message.funding.push(FundingSource.decode(reader, reader.uint32()));
          continue;
        }
        case 70: {
          if (tag === 565) {
            message.embedding.push(reader.float());

            continue;
          }

          if (tag === 562) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.embedding.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 71: {
          if (tag !== 570) {
            break;
          }

          message.embeddingModel = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Document {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      source: isSet(object.source) ? globalThis.String(object.source) : "",
      sourceNativeId: isSet(object.sourceNativeId)
        ? globalThis.String(object.sourceNativeId)
        : isSet(object.source_native_id)
        ? globalThis.String(object.source_native_id)
        : "",
      doi: isSet(object.doi) ? globalThis.String(object.doi) : undefined,
      pmid: isSet(object.pmid) ? globalThis.String(object.pmid) : undefined,
      pmcid: isSet(object.pmcid) ? globalThis.String(object.pmcid) : undefined,
      nctId: isSet(object.nctId)
        ? globalThis.String(object.nctId)
        : isSet(object.nct_id)
        ? globalThis.String(object.nct_id)
        : undefined,
      ictrpId: isSet(object.ictrpId)
        ? globalThis.String(object.ictrpId)
        : isSet(object.ictrp_id)
        ? globalThis.String(object.ictrp_id)
        : undefined,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      abstract: isSet(object.abstract) ? globalThis.String(object.abstract) : "",
      fullText: isSet(object.fullText)
        ? globalThis.String(object.fullText)
        : isSet(object.full_text)
        ? globalThis.String(object.full_text)
        : undefined,
      canonicalUrl: isSet(object.canonicalUrl)
        ? globalThis.String(object.canonicalUrl)
        : isSet(object.canonical_url)
        ? globalThis.String(object.canonical_url)
        : "",
      ingestedAt: isSet(object.ingestedAt)
        ? fromJsonTimestamp(object.ingestedAt)
        : isSet(object.ingested_at)
        ? fromJsonTimestamp(object.ingested_at)
        : undefined,
      sourceUpdatedAt: isSet(object.sourceUpdatedAt)
        ? fromJsonTimestamp(object.sourceUpdatedAt)
        : isSet(object.source_updated_at)
        ? fromJsonTimestamp(object.source_updated_at)
        : undefined,
      publishedAt: isSet(object.publishedAt)
        ? fromJsonTimestamp(object.publishedAt)
        : isSet(object.published_at)
        ? fromJsonTimestamp(object.published_at)
        : undefined,
      license: isSet(object.license) ? globalThis.String(object.license) : "",
      objectRawKey: isSet(object.objectRawKey)
        ? globalThis.String(object.objectRawKey)
        : isSet(object.object_raw_key)
        ? globalThis.String(object.object_raw_key)
        : "",
      authors: globalThis.Array.isArray(object?.authors)
        ? object.authors.map((e: any) => Author.fromJSON(e))
        : [],
      studyType: isSet(object.studyType)
        ? studyTypeFromJSON(object.studyType)
        : isSet(object.study_type)
        ? studyTypeFromJSON(object.study_type)
        : 0,
      meshTerms: globalThis.Array.isArray(object?.meshTerms)
        ? object.meshTerms.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.mesh_terms)
        ? object.mesh_terms.map((e: any) => globalThis.String(e))
        : [],
      keywords: globalThis.Array.isArray(object?.keywords)
        ? object.keywords.map((e: any) => globalThis.String(e))
        : [],
      journal: isSet(object.journal) ? Journal.fromJSON(object.journal) : undefined,
      trial: isSet(object.trial) ? Trial.fromJSON(object.trial) : undefined,
      regulatory: isSet(object.regulatory) ? Regulatory.fromJSON(object.regulatory) : undefined,
      citationCount: isSet(object.citationCount)
        ? globalThis.Number(object.citationCount)
        : isSet(object.citation_count)
        ? globalThis.Number(object.citation_count)
        : 0,
      citationPagerank: isSet(object.citationPagerank)
        ? globalThis.Number(object.citationPagerank)
        : isSet(object.citation_pagerank)
        ? globalThis.Number(object.citation_pagerank)
        : 0,
      funding: globalThis.Array.isArray(object?.funding)
        ? object.funding.map((e: any) => FundingSource.fromJSON(e))
        : [],
      embedding: globalThis.Array.isArray(object?.embedding)
        ? object.embedding.map((e: any) => globalThis.Number(e))
        : [],
      embeddingModel: isSet(object.embeddingModel)
        ? globalThis.String(object.embeddingModel)
        : isSet(object.embedding_model)
        ? globalThis.String(object.embedding_model)
        : "",
    };
  },

  toJSON(message: Document): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.source !== "") {
      obj.source = message.source;
    }
    if (message.sourceNativeId !== "") {
      obj.sourceNativeId = message.sourceNativeId;
    }
    if (message.doi !== undefined) {
      obj.doi = message.doi;
    }
    if (message.pmid !== undefined) {
      obj.pmid = message.pmid;
    }
    if (message.pmcid !== undefined) {
      obj.pmcid = message.pmcid;
    }
    if (message.nctId !== undefined) {
      obj.nctId = message.nctId;
    }
    if (message.ictrpId !== undefined) {
      obj.ictrpId = message.ictrpId;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.abstract !== "") {
      obj.abstract = message.abstract;
    }
    if (message.fullText !== undefined) {
      obj.fullText = message.fullText;
    }
    if (message.canonicalUrl !== "") {
      obj.canonicalUrl = message.canonicalUrl;
    }
    if (message.ingestedAt !== undefined) {
      obj.ingestedAt = message.ingestedAt.toISOString();
    }
    if (message.sourceUpdatedAt !== undefined) {
      obj.sourceUpdatedAt = message.sourceUpdatedAt.toISOString();
    }
    if (message.publishedAt !== undefined) {
      obj.publishedAt = message.publishedAt.toISOString();
    }
    if (message.license !== "") {
      obj.license = message.license;
    }
    if (message.objectRawKey !== "") {
      obj.objectRawKey = message.objectRawKey;
    }
    if (message.authors?.length) {
      obj.authors = message.authors.map((e) => Author.toJSON(e));
    }
    if (message.studyType !== 0) {
      obj.studyType = studyTypeToJSON(message.studyType);
    }
    if (message.meshTerms?.length) {
      obj.meshTerms = message.meshTerms;
    }
    if (message.keywords?.length) {
      obj.keywords = message.keywords;
    }
    if (message.journal !== undefined) {
      obj.journal = Journal.toJSON(message.journal);
    }
    if (message.trial !== undefined) {
      obj.trial = Trial.toJSON(message.trial);
    }
    if (message.regulatory !== undefined) {
      obj.regulatory = Regulatory.toJSON(message.regulatory);
    }
    if (message.citationCount !== 0) {
      obj.citationCount = Math.round(message.citationCount);
    }
    if (message.citationPagerank !== 0) {
      obj.citationPagerank = message.citationPagerank;
    }
    if (message.funding?.length) {
      obj.funding = message.funding.map((e) => FundingSource.toJSON(e));
    }
    if (message.embedding?.length) {
      obj.embedding = message.embedding;
    }
    if (message.embeddingModel !== "") {
      obj.embeddingModel = message.embeddingModel;
    }
    return obj;
  },

  create(base?: DeepPartial<Document>): Document {
    return Document.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Document>): Document {
    const message = createBaseDocument();
    message.id = object.id ?? "";
    message.source = object.source ?? "";
    message.sourceNativeId = object.sourceNativeId ?? "";
    message.doi = object.doi ?? undefined;
    message.pmid = object.pmid ?? undefined;
    message.pmcid = object.pmcid ?? undefined;
    message.nctId = object.nctId ?? undefined;
    message.ictrpId = object.ictrpId ?? undefined;
    message.title = object.title ?? "";
    message.abstract = object.abstract ?? "";
    message.fullText = object.fullText ?? undefined;
    message.canonicalUrl = object.canonicalUrl ?? "";
    message.ingestedAt = object.ingestedAt ?? undefined;
    message.sourceUpdatedAt = object.sourceUpdatedAt ?? undefined;
    message.publishedAt = object.publishedAt ?? undefined;
    message.license = object.license ?? "";
    message.objectRawKey = object.objectRawKey ?? "";
    message.authors = object.authors?.map((e) => Author.fromPartial(e)) || [];
    message.studyType = object.studyType ?? 0;
    message.meshTerms = object.meshTerms?.map((e) => e) || [];
    message.keywords = object.keywords?.map((e) => e) || [];
    message.journal = (object.journal !== undefined && object.journal !== null)
      ? Journal.fromPartial(object.journal)
      : undefined;
    message.trial = (object.trial !== undefined && object.trial !== null) ? Trial.fromPartial(object.trial) : undefined;
    message.regulatory = (object.regulatory !== undefined && object.regulatory !== null)
      ? Regulatory.fromPartial(object.regulatory)
      : undefined;
    message.citationCount = object.citationCount ?? 0;
    message.citationPagerank = object.citationPagerank ?? 0;
    message.funding = object.funding?.map((e) => FundingSource.fromPartial(e)) || [];
    message.embedding = object.embedding?.map((e) => e) || [];
    message.embeddingModel = object.embeddingModel ?? "";
    return message;
  },
};

function createBaseAuthor(): Author {
  return {
    displayName: "",
    givenName: undefined,
    familyName: undefined,
    orcid: undefined,
    affiliation: undefined,
    payments: [],
  };
}

export const Author: MessageFns<Author> = {
  encode(message: Author, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.displayName !== "") {
      writer.uint32(10).string(message.displayName);
    }
    if (message.givenName !== undefined) {
      writer.uint32(18).string(message.givenName);
    }
    if (message.familyName !== undefined) {
      writer.uint32(26).string(message.familyName);
    }
    if (message.orcid !== undefined) {
      writer.uint32(34).string(message.orcid);
    }
    if (message.affiliation !== undefined) {
      writer.uint32(42).string(message.affiliation);
    }
    for (const v of message.payments) {
      AuthorPayment.encode(v!, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Author {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.givenName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.familyName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.orcid = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.affiliation = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.payments.push(AuthorPayment.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Author {
    return {
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
        ? globalThis.String(object.display_name)
        : "",
      givenName: isSet(object.givenName)
        ? globalThis.String(object.givenName)
        : isSet(object.given_name)
        ? globalThis.String(object.given_name)
        : undefined,
      familyName: isSet(object.familyName)
        ? globalThis.String(object.familyName)
        : isSet(object.family_name)
        ? globalThis.String(object.family_name)
        : undefined,
      orcid: isSet(object.orcid) ? globalThis.String(object.orcid) : undefined,
      affiliation: isSet(object.affiliation) ? globalThis.String(object.affiliation) : undefined,
      payments: globalThis.Array.isArray(object?.payments)
        ? object.payments.map((e: any) => AuthorPayment.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Author): unknown {
    const obj: any = {};
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.givenName !== undefined) {
      obj.givenName = message.givenName;
    }
    if (message.familyName !== undefined) {
      obj.familyName = message.familyName;
    }
    if (message.orcid !== undefined) {
      obj.orcid = message.orcid;
    }
    if (message.affiliation !== undefined) {
      obj.affiliation = message.affiliation;
    }
    if (message.payments?.length) {
      obj.payments = message.payments.map((e) => AuthorPayment.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<Author>): Author {
    return Author.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Author>): Author {
    const message = createBaseAuthor();
    message.displayName = object.displayName ?? "";
    message.givenName = object.givenName ?? undefined;
    message.familyName = object.familyName ?? undefined;
    message.orcid = object.orcid ?? undefined;
    message.affiliation = object.affiliation ?? undefined;
    message.payments = object.payments?.map((e) => AuthorPayment.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAuthorPayment(): AuthorPayment {
  return { sponsorName: "", year: "", amountUsd: 0, paymentType: "", sourceRecordId: "" };
}

export const AuthorPayment: MessageFns<AuthorPayment> = {
  encode(message: AuthorPayment, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sponsorName !== "") {
      writer.uint32(10).string(message.sponsorName);
    }
    if (message.year !== "") {
      writer.uint32(18).string(message.year);
    }
    if (message.amountUsd !== 0) {
      writer.uint32(25).double(message.amountUsd);
    }
    if (message.paymentType !== "") {
      writer.uint32(34).string(message.paymentType);
    }
    if (message.sourceRecordId !== "") {
      writer.uint32(42).string(message.sourceRecordId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthorPayment {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthorPayment();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sponsorName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.year = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.amountUsd = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.paymentType = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sourceRecordId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthorPayment {
    return {
      sponsorName: isSet(object.sponsorName)
        ? globalThis.String(object.sponsorName)
        : isSet(object.sponsor_name)
        ? globalThis.String(object.sponsor_name)
        : "",
      year: isSet(object.year) ? globalThis.String(object.year) : "",
      amountUsd: isSet(object.amountUsd)
        ? globalThis.Number(object.amountUsd)
        : isSet(object.amount_usd)
        ? globalThis.Number(object.amount_usd)
        : 0,
      paymentType: isSet(object.paymentType)
        ? globalThis.String(object.paymentType)
        : isSet(object.payment_type)
        ? globalThis.String(object.payment_type)
        : "",
      sourceRecordId: isSet(object.sourceRecordId)
        ? globalThis.String(object.sourceRecordId)
        : isSet(object.source_record_id)
        ? globalThis.String(object.source_record_id)
        : "",
    };
  },

  toJSON(message: AuthorPayment): unknown {
    const obj: any = {};
    if (message.sponsorName !== "") {
      obj.sponsorName = message.sponsorName;
    }
    if (message.year !== "") {
      obj.year = message.year;
    }
    if (message.amountUsd !== 0) {
      obj.amountUsd = message.amountUsd;
    }
    if (message.paymentType !== "") {
      obj.paymentType = message.paymentType;
    }
    if (message.sourceRecordId !== "") {
      obj.sourceRecordId = message.sourceRecordId;
    }
    return obj;
  },

  create(base?: DeepPartial<AuthorPayment>): AuthorPayment {
    return AuthorPayment.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AuthorPayment>): AuthorPayment {
    const message = createBaseAuthorPayment();
    message.sponsorName = object.sponsorName ?? "";
    message.year = object.year ?? "";
    message.amountUsd = object.amountUsd ?? 0;
    message.paymentType = object.paymentType ?? "";
    message.sourceRecordId = object.sourceRecordId ?? "";
    return message;
  },
};

function createBaseJournal(): Journal {
  return { name: "", issn: undefined, publisher: undefined, impactFactor: undefined, isPredatory: false };
}

export const Journal: MessageFns<Journal> = {
  encode(message: Journal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.issn !== undefined) {
      writer.uint32(18).string(message.issn);
    }
    if (message.publisher !== undefined) {
      writer.uint32(26).string(message.publisher);
    }
    if (message.impactFactor !== undefined) {
      writer.uint32(33).double(message.impactFactor);
    }
    if (message.isPredatory !== false) {
      writer.uint32(40).bool(message.isPredatory);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Journal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJournal();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.issn = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.publisher = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.impactFactor = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isPredatory = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Journal {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      issn: isSet(object.issn) ? globalThis.String(object.issn) : undefined,
      publisher: isSet(object.publisher) ? globalThis.String(object.publisher) : undefined,
      impactFactor: isSet(object.impactFactor)
        ? globalThis.Number(object.impactFactor)
        : isSet(object.impact_factor)
        ? globalThis.Number(object.impact_factor)
        : undefined,
      isPredatory: isSet(object.isPredatory)
        ? globalThis.Boolean(object.isPredatory)
        : isSet(object.is_predatory)
        ? globalThis.Boolean(object.is_predatory)
        : false,
    };
  },

  toJSON(message: Journal): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.issn !== undefined) {
      obj.issn = message.issn;
    }
    if (message.publisher !== undefined) {
      obj.publisher = message.publisher;
    }
    if (message.impactFactor !== undefined) {
      obj.impactFactor = message.impactFactor;
    }
    if (message.isPredatory !== false) {
      obj.isPredatory = message.isPredatory;
    }
    return obj;
  },

  create(base?: DeepPartial<Journal>): Journal {
    return Journal.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Journal>): Journal {
    const message = createBaseJournal();
    message.name = object.name ?? "";
    message.issn = object.issn ?? undefined;
    message.publisher = object.publisher ?? undefined;
    message.impactFactor = object.impactFactor ?? undefined;
    message.isPredatory = object.isPredatory ?? false;
    return message;
  },
};

function createBaseTrial(): Trial {
  return {
    registry: "",
    status: "",
    phase: "",
    conditions: [],
    interventions: [],
    locations: [],
    enrollment: undefined,
    startDate: undefined,
    completionDate: undefined,
    primaryOutcome: undefined,
  };
}

export const Trial: MessageFns<Trial> = {
  encode(message: Trial, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.registry !== "") {
      writer.uint32(10).string(message.registry);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.phase !== "") {
      writer.uint32(26).string(message.phase);
    }
    for (const v of message.conditions) {
      writer.uint32(34).string(v!);
    }
    for (const v of message.interventions) {
      writer.uint32(42).string(v!);
    }
    for (const v of message.locations) {
      writer.uint32(50).string(v!);
    }
    if (message.enrollment !== undefined) {
      writer.uint32(56).int64(message.enrollment);
    }
    if (message.startDate !== undefined) {
      Timestamp.encode(toTimestamp(message.startDate), writer.uint32(66).fork()).join();
    }
    if (message.completionDate !== undefined) {
      Timestamp.encode(toTimestamp(message.completionDate), writer.uint32(74).fork()).join();
    }
    if (message.primaryOutcome !== undefined) {
      writer.uint32(82).string(message.primaryOutcome);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Trial {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrial();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.registry = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.phase = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.conditions.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.interventions.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.locations.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.enrollment = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.startDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.completionDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.primaryOutcome = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Trial {
    return {
      registry: isSet(object.registry) ? globalThis.String(object.registry) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      phase: isSet(object.phase) ? globalThis.String(object.phase) : "",
      conditions: globalThis.Array.isArray(object?.conditions)
        ? object.conditions.map((e: any) => globalThis.String(e))
        : [],
      interventions: globalThis.Array.isArray(object?.interventions)
        ? object.interventions.map((e: any) => globalThis.String(e))
        : [],
      locations: globalThis.Array.isArray(object?.locations)
        ? object.locations.map((e: any) => globalThis.String(e))
        : [],
      enrollment: isSet(object.enrollment) ? globalThis.Number(object.enrollment) : undefined,
      startDate: isSet(object.startDate)
        ? fromJsonTimestamp(object.startDate)
        : isSet(object.start_date)
        ? fromJsonTimestamp(object.start_date)
        : undefined,
      completionDate: isSet(object.completionDate)
        ? fromJsonTimestamp(object.completionDate)
        : isSet(object.completion_date)
        ? fromJsonTimestamp(object.completion_date)
        : undefined,
      primaryOutcome: isSet(object.primaryOutcome)
        ? globalThis.String(object.primaryOutcome)
        : isSet(object.primary_outcome)
        ? globalThis.String(object.primary_outcome)
        : undefined,
    };
  },

  toJSON(message: Trial): unknown {
    const obj: any = {};
    if (message.registry !== "") {
      obj.registry = message.registry;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.phase !== "") {
      obj.phase = message.phase;
    }
    if (message.conditions?.length) {
      obj.conditions = message.conditions;
    }
    if (message.interventions?.length) {
      obj.interventions = message.interventions;
    }
    if (message.locations?.length) {
      obj.locations = message.locations;
    }
    if (message.enrollment !== undefined) {
      obj.enrollment = Math.round(message.enrollment);
    }
    if (message.startDate !== undefined) {
      obj.startDate = message.startDate.toISOString();
    }
    if (message.completionDate !== undefined) {
      obj.completionDate = message.completionDate.toISOString();
    }
    if (message.primaryOutcome !== undefined) {
      obj.primaryOutcome = message.primaryOutcome;
    }
    return obj;
  },

  create(base?: DeepPartial<Trial>): Trial {
    return Trial.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Trial>): Trial {
    const message = createBaseTrial();
    message.registry = object.registry ?? "";
    message.status = object.status ?? "";
    message.phase = object.phase ?? "";
    message.conditions = object.conditions?.map((e) => e) || [];
    message.interventions = object.interventions?.map((e) => e) || [];
    message.locations = object.locations?.map((e) => e) || [];
    message.enrollment = object.enrollment ?? undefined;
    message.startDate = object.startDate ?? undefined;
    message.completionDate = object.completionDate ?? undefined;
    message.primaryOutcome = object.primaryOutcome ?? undefined;
    return message;
  },
};

function createBaseRegulatory(): Regulatory {
  return {
    agency: "",
    eventType: "",
    productName: "",
    drugClass: undefined,
    recallClass: undefined,
    reason: undefined,
    action: undefined,
  };
}

export const Regulatory: MessageFns<Regulatory> = {
  encode(message: Regulatory, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.agency !== "") {
      writer.uint32(10).string(message.agency);
    }
    if (message.eventType !== "") {
      writer.uint32(18).string(message.eventType);
    }
    if (message.productName !== "") {
      writer.uint32(26).string(message.productName);
    }
    if (message.drugClass !== undefined) {
      writer.uint32(34).string(message.drugClass);
    }
    if (message.recallClass !== undefined) {
      writer.uint32(42).string(message.recallClass);
    }
    if (message.reason !== undefined) {
      writer.uint32(50).string(message.reason);
    }
    if (message.action !== undefined) {
      writer.uint32(58).string(message.action);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Regulatory {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegulatory();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.agency = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.eventType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.productName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.drugClass = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.recallClass = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.action = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Regulatory {
    return {
      agency: isSet(object.agency) ? globalThis.String(object.agency) : "",
      eventType: isSet(object.eventType)
        ? globalThis.String(object.eventType)
        : isSet(object.event_type)
        ? globalThis.String(object.event_type)
        : "",
      productName: isSet(object.productName)
        ? globalThis.String(object.productName)
        : isSet(object.product_name)
        ? globalThis.String(object.product_name)
        : "",
      drugClass: isSet(object.drugClass)
        ? globalThis.String(object.drugClass)
        : isSet(object.drug_class)
        ? globalThis.String(object.drug_class)
        : undefined,
      recallClass: isSet(object.recallClass)
        ? globalThis.String(object.recallClass)
        : isSet(object.recall_class)
        ? globalThis.String(object.recall_class)
        : undefined,
      reason: isSet(object.reason) ? globalThis.String(object.reason) : undefined,
      action: isSet(object.action) ? globalThis.String(object.action) : undefined,
    };
  },

  toJSON(message: Regulatory): unknown {
    const obj: any = {};
    if (message.agency !== "") {
      obj.agency = message.agency;
    }
    if (message.eventType !== "") {
      obj.eventType = message.eventType;
    }
    if (message.productName !== "") {
      obj.productName = message.productName;
    }
    if (message.drugClass !== undefined) {
      obj.drugClass = message.drugClass;
    }
    if (message.recallClass !== undefined) {
      obj.recallClass = message.recallClass;
    }
    if (message.reason !== undefined) {
      obj.reason = message.reason;
    }
    if (message.action !== undefined) {
      obj.action = message.action;
    }
    return obj;
  },

  create(base?: DeepPartial<Regulatory>): Regulatory {
    return Regulatory.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Regulatory>): Regulatory {
    const message = createBaseRegulatory();
    message.agency = object.agency ?? "";
    message.eventType = object.eventType ?? "";
    message.productName = object.productName ?? "";
    message.drugClass = object.drugClass ?? undefined;
    message.recallClass = object.recallClass ?? undefined;
    message.reason = object.reason ?? undefined;
    message.action = object.action ?? undefined;
    return message;
  },
};

function createBaseFundingSource(): FundingSource {
  return { funder: "", grantId: undefined, amountUsd: undefined, fiscalYear: undefined };
}

export const FundingSource: MessageFns<FundingSource> = {
  encode(message: FundingSource, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.funder !== "") {
      writer.uint32(10).string(message.funder);
    }
    if (message.grantId !== undefined) {
      writer.uint32(18).string(message.grantId);
    }
    if (message.amountUsd !== undefined) {
      writer.uint32(25).double(message.amountUsd);
    }
    if (message.fiscalYear !== undefined) {
      writer.uint32(34).string(message.fiscalYear);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FundingSource {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFundingSource();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.funder = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.grantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.amountUsd = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.fiscalYear = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FundingSource {
    return {
      funder: isSet(object.funder) ? globalThis.String(object.funder) : "",
      grantId: isSet(object.grantId)
        ? globalThis.String(object.grantId)
        : isSet(object.grant_id)
        ? globalThis.String(object.grant_id)
        : undefined,
      amountUsd: isSet(object.amountUsd)
        ? globalThis.Number(object.amountUsd)
        : isSet(object.amount_usd)
        ? globalThis.Number(object.amount_usd)
        : undefined,
      fiscalYear: isSet(object.fiscalYear)
        ? globalThis.String(object.fiscalYear)
        : isSet(object.fiscal_year)
        ? globalThis.String(object.fiscal_year)
        : undefined,
    };
  },

  toJSON(message: FundingSource): unknown {
    const obj: any = {};
    if (message.funder !== "") {
      obj.funder = message.funder;
    }
    if (message.grantId !== undefined) {
      obj.grantId = message.grantId;
    }
    if (message.amountUsd !== undefined) {
      obj.amountUsd = message.amountUsd;
    }
    if (message.fiscalYear !== undefined) {
      obj.fiscalYear = message.fiscalYear;
    }
    return obj;
  },

  create(base?: DeepPartial<FundingSource>): FundingSource {
    return FundingSource.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FundingSource>): FundingSource {
    const message = createBaseFundingSource();
    message.funder = object.funder ?? "";
    message.grantId = object.grantId ?? undefined;
    message.amountUsd = object.amountUsd ?? undefined;
    message.fiscalYear = object.fiscalYear ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
