// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: evidencelens/v1/embedder.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type ClientUnaryCall,
  type handleBidiStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "evidencelens.v1";

export interface EmbedRequest {
  /**
   * Caller-chosen id propagated to the response. Required because the
   * server may reorder under dynamic batching. Use a uuid or any
   * monotonic counter that's unique within the stream.
   */
  requestId: string;
  /**
   * Texts to embed. The server treats each entry independently — it does
   * not produce a single mean-pooled vector across the array. The
   * processor mean-pools per-document at its own layer.
   *
   * Length cap: 32 per message. Longer batches will be split server-side
   * and merged into a single response with the same request_id.
   */
  texts: string[];
}

export interface EmbedResponse {
  requestId: string;
  embeddings: EmbeddingVector[];
  /**
   * Identifies the model that produced these vectors. Critical for
   * downstream consumers (e.g. Milvus collection_name="evidence_v1"
   * assumes 1024-d BGE-M3; if the embedder degrades to 384-d the indexer
   * must reject and the operator must rebuild the collection).
   */
  embeddingModel: string;
}

export interface EmbeddingVector {
  values: number[];
  /**
   * 1024 (BGE-M3) or 384 (BGE-small-en-v1.5 fallback). Stated explicitly
   * so consumers can validate before write without computing length.
   */
  dim: number;
}

export interface EmbedderHealthzRequest {
}

export interface EmbedderHealthzResponse {
  /**
   * "ok" — GPU + BGE-M3 healthy.
   * "degraded" — running CPU fallback (BGE-small-en-v1.5, 384-d).
   * "down" — neither path serving.
   */
  status: string;
  /** Active model identifier. Same value will appear in EmbedResponse. */
  embeddingModel: string;
  /** Free-text reason populated when status != "ok". */
  detail: string;
  checkedAt: Date | undefined;
}

function createBaseEmbedRequest(): EmbedRequest {
  return { requestId: "", texts: [] };
}

export const EmbedRequest: MessageFns<EmbedRequest> = {
  encode(message: EmbedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    for (const v of message.texts) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmbedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmbedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.texts.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmbedRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      texts: globalThis.Array.isArray(object?.texts) ? object.texts.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: EmbedRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.texts?.length) {
      obj.texts = message.texts;
    }
    return obj;
  },

  create(base?: DeepPartial<EmbedRequest>): EmbedRequest {
    return EmbedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EmbedRequest>): EmbedRequest {
    const message = createBaseEmbedRequest();
    message.requestId = object.requestId ?? "";
    message.texts = object.texts?.map((e) => e) || [];
    return message;
  },
};

function createBaseEmbedResponse(): EmbedResponse {
  return { requestId: "", embeddings: [], embeddingModel: "" };
}

export const EmbedResponse: MessageFns<EmbedResponse> = {
  encode(message: EmbedResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    for (const v of message.embeddings) {
      EmbeddingVector.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.embeddingModel !== "") {
      writer.uint32(26).string(message.embeddingModel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmbedResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmbedResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.embeddings.push(EmbeddingVector.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.embeddingModel = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmbedResponse {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      embeddings: globalThis.Array.isArray(object?.embeddings)
        ? object.embeddings.map((e: any) => EmbeddingVector.fromJSON(e))
        : [],
      embeddingModel: isSet(object.embeddingModel)
        ? globalThis.String(object.embeddingModel)
        : isSet(object.embedding_model)
        ? globalThis.String(object.embedding_model)
        : "",
    };
  },

  toJSON(message: EmbedResponse): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.embeddings?.length) {
      obj.embeddings = message.embeddings.map((e) => EmbeddingVector.toJSON(e));
    }
    if (message.embeddingModel !== "") {
      obj.embeddingModel = message.embeddingModel;
    }
    return obj;
  },

  create(base?: DeepPartial<EmbedResponse>): EmbedResponse {
    return EmbedResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EmbedResponse>): EmbedResponse {
    const message = createBaseEmbedResponse();
    message.requestId = object.requestId ?? "";
    message.embeddings = object.embeddings?.map((e) => EmbeddingVector.fromPartial(e)) || [];
    message.embeddingModel = object.embeddingModel ?? "";
    return message;
  },
};

function createBaseEmbeddingVector(): EmbeddingVector {
  return { values: [], dim: 0 };
}

export const EmbeddingVector: MessageFns<EmbeddingVector> = {
  encode(message: EmbeddingVector, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.values) {
      writer.float(v);
    }
    writer.join();
    if (message.dim !== 0) {
      writer.uint32(16).int32(message.dim);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmbeddingVector {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmbeddingVector();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 13) {
            message.values.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.values.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.dim = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmbeddingVector {
    return {
      values: globalThis.Array.isArray(object?.values) ? object.values.map((e: any) => globalThis.Number(e)) : [],
      dim: isSet(object.dim) ? globalThis.Number(object.dim) : 0,
    };
  },

  toJSON(message: EmbeddingVector): unknown {
    const obj: any = {};
    if (message.values?.length) {
      obj.values = message.values;
    }
    if (message.dim !== 0) {
      obj.dim = Math.round(message.dim);
    }
    return obj;
  },

  create(base?: DeepPartial<EmbeddingVector>): EmbeddingVector {
    return EmbeddingVector.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EmbeddingVector>): EmbeddingVector {
    const message = createBaseEmbeddingVector();
    message.values = object.values?.map((e) => e) || [];
    message.dim = object.dim ?? 0;
    return message;
  },
};

function createBaseEmbedderHealthzRequest(): EmbedderHealthzRequest {
  return {};
}

export const EmbedderHealthzRequest: MessageFns<EmbedderHealthzRequest> = {
  encode(_: EmbedderHealthzRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmbedderHealthzRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmbedderHealthzRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): EmbedderHealthzRequest {
    return {};
  },

  toJSON(_: EmbedderHealthzRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<EmbedderHealthzRequest>): EmbedderHealthzRequest {
    return EmbedderHealthzRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<EmbedderHealthzRequest>): EmbedderHealthzRequest {
    const message = createBaseEmbedderHealthzRequest();
    return message;
  },
};

function createBaseEmbedderHealthzResponse(): EmbedderHealthzResponse {
  return { status: "", embeddingModel: "", detail: "", checkedAt: undefined };
}

export const EmbedderHealthzResponse: MessageFns<EmbedderHealthzResponse> = {
  encode(message: EmbedderHealthzResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.embeddingModel !== "") {
      writer.uint32(18).string(message.embeddingModel);
    }
    if (message.detail !== "") {
      writer.uint32(26).string(message.detail);
    }
    if (message.checkedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.checkedAt), writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmbedderHealthzResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmbedderHealthzResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.embeddingModel = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.detail = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.checkedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmbedderHealthzResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      embeddingModel: isSet(object.embeddingModel)
        ? globalThis.String(object.embeddingModel)
        : isSet(object.embedding_model)
        ? globalThis.String(object.embedding_model)
        : "",
      detail: isSet(object.detail) ? globalThis.String(object.detail) : "",
      checkedAt: isSet(object.checkedAt)
        ? fromJsonTimestamp(object.checkedAt)
        : isSet(object.checked_at)
        ? fromJsonTimestamp(object.checked_at)
        : undefined,
    };
  },

  toJSON(message: EmbedderHealthzResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.embeddingModel !== "") {
      obj.embeddingModel = message.embeddingModel;
    }
    if (message.detail !== "") {
      obj.detail = message.detail;
    }
    if (message.checkedAt !== undefined) {
      obj.checkedAt = message.checkedAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<EmbedderHealthzResponse>): EmbedderHealthzResponse {
    return EmbedderHealthzResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EmbedderHealthzResponse>): EmbedderHealthzResponse {
    const message = createBaseEmbedderHealthzResponse();
    message.status = object.status ?? "";
    message.embeddingModel = object.embeddingModel ?? "";
    message.detail = object.detail ?? "";
    message.checkedAt = object.checkedAt ?? undefined;
    return message;
  },
};

export type EmbedderServiceService = typeof EmbedderServiceService;
export const EmbedderServiceService = {
  /**
   * Bidirectional streaming embedding. The server batches incoming
   * requests dynamically (batch=32, max-wait=25ms) for GPU throughput.
   * Responses are emitted in arrival order; clients should match by
   * request_id rather than position.
   */
  embed: {
    path: "/evidencelens.v1.EmbedderService/Embed" as const,
    requestStream: true as const,
    responseStream: true as const,
    requestSerialize: (value: EmbedRequest): Buffer => Buffer.from(EmbedRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): EmbedRequest => EmbedRequest.decode(value),
    responseSerialize: (value: EmbedResponse): Buffer => Buffer.from(EmbedResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): EmbedResponse => EmbedResponse.decode(value),
  },
  /**
   * Single-shot variant for callers that don't want to manage a stream
   * (e.g. one-off CLI tools, tests). Internally rate-limited to avoid
   * starving the streaming queue.
   */
  embedOnce: {
    path: "/evidencelens.v1.EmbedderService/EmbedOnce" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: EmbedRequest): Buffer => Buffer.from(EmbedRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): EmbedRequest => EmbedRequest.decode(value),
    responseSerialize: (value: EmbedResponse): Buffer => Buffer.from(EmbedResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): EmbedResponse => EmbedResponse.decode(value),
  },
  /**
   * Health probe. Returns "degraded" when running on the CPU fallback
   * (BGE-small-en-v1.5, 384-d) instead of GPU BGE-M3 (1024-d). Consumers
   * should validate `embedding_model` on every response, not just at
   * startup.
   */
  healthz: {
    path: "/evidencelens.v1.EmbedderService/Healthz" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: EmbedderHealthzRequest): Buffer =>
      Buffer.from(EmbedderHealthzRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): EmbedderHealthzRequest => EmbedderHealthzRequest.decode(value),
    responseSerialize: (value: EmbedderHealthzResponse): Buffer =>
      Buffer.from(EmbedderHealthzResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): EmbedderHealthzResponse => EmbedderHealthzResponse.decode(value),
  },
} as const;

export interface EmbedderServiceServer extends UntypedServiceImplementation {
  /**
   * Bidirectional streaming embedding. The server batches incoming
   * requests dynamically (batch=32, max-wait=25ms) for GPU throughput.
   * Responses are emitted in arrival order; clients should match by
   * request_id rather than position.
   */
  embed: handleBidiStreamingCall<EmbedRequest, EmbedResponse>;
  /**
   * Single-shot variant for callers that don't want to manage a stream
   * (e.g. one-off CLI tools, tests). Internally rate-limited to avoid
   * starving the streaming queue.
   */
  embedOnce: handleUnaryCall<EmbedRequest, EmbedResponse>;
  /**
   * Health probe. Returns "degraded" when running on the CPU fallback
   * (BGE-small-en-v1.5, 384-d) instead of GPU BGE-M3 (1024-d). Consumers
   * should validate `embedding_model` on every response, not just at
   * startup.
   */
  healthz: handleUnaryCall<EmbedderHealthzRequest, EmbedderHealthzResponse>;
}

export interface EmbedderServiceClient extends Client {
  /**
   * Bidirectional streaming embedding. The server batches incoming
   * requests dynamically (batch=32, max-wait=25ms) for GPU throughput.
   * Responses are emitted in arrival order; clients should match by
   * request_id rather than position.
   */
  embed(): ClientDuplexStream<EmbedRequest, EmbedResponse>;
  embed(options: Partial<CallOptions>): ClientDuplexStream<EmbedRequest, EmbedResponse>;
  embed(metadata: Metadata, options?: Partial<CallOptions>): ClientDuplexStream<EmbedRequest, EmbedResponse>;
  /**
   * Single-shot variant for callers that don't want to manage a stream
   * (e.g. one-off CLI tools, tests). Internally rate-limited to avoid
   * starving the streaming queue.
   */
  embedOnce(
    request: EmbedRequest,
    callback: (error: ServiceError | null, response: EmbedResponse) => void,
  ): ClientUnaryCall;
  embedOnce(
    request: EmbedRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: EmbedResponse) => void,
  ): ClientUnaryCall;
  embedOnce(
    request: EmbedRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: EmbedResponse) => void,
  ): ClientUnaryCall;
  /**
   * Health probe. Returns "degraded" when running on the CPU fallback
   * (BGE-small-en-v1.5, 384-d) instead of GPU BGE-M3 (1024-d). Consumers
   * should validate `embedding_model` on every response, not just at
   * startup.
   */
  healthz(
    request: EmbedderHealthzRequest,
    callback: (error: ServiceError | null, response: EmbedderHealthzResponse) => void,
  ): ClientUnaryCall;
  healthz(
    request: EmbedderHealthzRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: EmbedderHealthzResponse) => void,
  ): ClientUnaryCall;
  healthz(
    request: EmbedderHealthzRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: EmbedderHealthzResponse) => void,
  ): ClientUnaryCall;
}

export const EmbedderServiceClient = makeGenericClientConstructor(
  EmbedderServiceService,
  "evidencelens.v1.EmbedderService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): EmbedderServiceClient;
  service: typeof EmbedderServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
