// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: evidencelens/v1/events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../../google/protobuf/timestamp";
import { Document } from "./document";

export const protobufPackage = "evidencelens.v1";

/**
 * Published by ingesters to GCP Pub/Sub topic `raw-docs`. The payload
 * itself does not contain the document body — consumers fetch from the
 * object store (MinIO) at `object_key` to keep Pub/Sub message size small.
 */
export interface RawDocEvent {
  source: string;
  docId: string;
  objectKey: string;
  ingestedAt: Date | undefined;
}

/**
 * Published by the processor to NATS subject `indexable-docs.{source}`
 * after parsing, normalizing, entity-linking, chunking, embedding, and
 * joining Open Payments. The full enriched Document is inline because the
 * indexer needs every field and NATS has no per-message size penalty
 * within JetStream stream limits.
 */
export interface IndexableDocEvent {
  document: Document | undefined;
  processedAt: Date | undefined;
}

/**
 * Published by the FDA recall priority lane in the openFDA ingester to NATS
 * subject `recall-fanout`. The frontend's RecallTicker subscribes via the
 * gateway WebSocket. SLO: end-to-end ≤ 1 minute p95 (spec §14.1).
 */
export interface RecallEvent {
  recallId: string;
  agency: string;
  productName: string;
  drugClass: string;
  /** FDA classification: "I" (highest risk) | "II" | "III". */
  recallClass: string;
  emittedAt: Date | undefined;
}

/**
 * Published by the click-logger Cloudflare Worker to GCP Pub/Sub topic
 * `click-events`. Drains nightly into BigQuery `analytics.clicks` table
 * (partitioned by server_ts, clustered by variant + query_text). Used by
 * the LTR retraining job and the interleaving evaluator.
 */
export interface ClickEvent {
  sessionId: string;
  queryId: string;
  clickedDocId: string;
  clickedPosition: number;
  /**
   * A/B variant for whichever experiment was active when the result was
   * shown. Empty when no experiment is active. See spec §11.
   */
  variant: string;
  at: Date | undefined;
}

function createBaseRawDocEvent(): RawDocEvent {
  return { source: "", docId: "", objectKey: "", ingestedAt: undefined };
}

export const RawDocEvent: MessageFns<RawDocEvent> = {
  encode(message: RawDocEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.source !== "") {
      writer.uint32(10).string(message.source);
    }
    if (message.docId !== "") {
      writer.uint32(18).string(message.docId);
    }
    if (message.objectKey !== "") {
      writer.uint32(26).string(message.objectKey);
    }
    if (message.ingestedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.ingestedAt), writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RawDocEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRawDocEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.source = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.docId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.objectKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ingestedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RawDocEvent {
    return {
      source: isSet(object.source) ? globalThis.String(object.source) : "",
      docId: isSet(object.docId)
        ? globalThis.String(object.docId)
        : isSet(object.doc_id)
        ? globalThis.String(object.doc_id)
        : "",
      objectKey: isSet(object.objectKey)
        ? globalThis.String(object.objectKey)
        : isSet(object.object_key)
        ? globalThis.String(object.object_key)
        : "",
      ingestedAt: isSet(object.ingestedAt)
        ? fromJsonTimestamp(object.ingestedAt)
        : isSet(object.ingested_at)
        ? fromJsonTimestamp(object.ingested_at)
        : undefined,
    };
  },

  toJSON(message: RawDocEvent): unknown {
    const obj: any = {};
    if (message.source !== "") {
      obj.source = message.source;
    }
    if (message.docId !== "") {
      obj.docId = message.docId;
    }
    if (message.objectKey !== "") {
      obj.objectKey = message.objectKey;
    }
    if (message.ingestedAt !== undefined) {
      obj.ingestedAt = message.ingestedAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<RawDocEvent>): RawDocEvent {
    return RawDocEvent.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RawDocEvent>): RawDocEvent {
    const message = createBaseRawDocEvent();
    message.source = object.source ?? "";
    message.docId = object.docId ?? "";
    message.objectKey = object.objectKey ?? "";
    message.ingestedAt = object.ingestedAt ?? undefined;
    return message;
  },
};

function createBaseIndexableDocEvent(): IndexableDocEvent {
  return { document: undefined, processedAt: undefined };
}

export const IndexableDocEvent: MessageFns<IndexableDocEvent> = {
  encode(message: IndexableDocEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.document !== undefined) {
      Document.encode(message.document, writer.uint32(10).fork()).join();
    }
    if (message.processedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.processedAt), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IndexableDocEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIndexableDocEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.document = Document.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.processedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IndexableDocEvent {
    return {
      document: isSet(object.document) ? Document.fromJSON(object.document) : undefined,
      processedAt: isSet(object.processedAt)
        ? fromJsonTimestamp(object.processedAt)
        : isSet(object.processed_at)
        ? fromJsonTimestamp(object.processed_at)
        : undefined,
    };
  },

  toJSON(message: IndexableDocEvent): unknown {
    const obj: any = {};
    if (message.document !== undefined) {
      obj.document = Document.toJSON(message.document);
    }
    if (message.processedAt !== undefined) {
      obj.processedAt = message.processedAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<IndexableDocEvent>): IndexableDocEvent {
    return IndexableDocEvent.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<IndexableDocEvent>): IndexableDocEvent {
    const message = createBaseIndexableDocEvent();
    message.document = (object.document !== undefined && object.document !== null)
      ? Document.fromPartial(object.document)
      : undefined;
    message.processedAt = object.processedAt ?? undefined;
    return message;
  },
};

function createBaseRecallEvent(): RecallEvent {
  return { recallId: "", agency: "", productName: "", drugClass: "", recallClass: "", emittedAt: undefined };
}

export const RecallEvent: MessageFns<RecallEvent> = {
  encode(message: RecallEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.recallId !== "") {
      writer.uint32(10).string(message.recallId);
    }
    if (message.agency !== "") {
      writer.uint32(18).string(message.agency);
    }
    if (message.productName !== "") {
      writer.uint32(26).string(message.productName);
    }
    if (message.drugClass !== "") {
      writer.uint32(34).string(message.drugClass);
    }
    if (message.recallClass !== "") {
      writer.uint32(42).string(message.recallClass);
    }
    if (message.emittedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.emittedAt), writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecallEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecallEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.recallId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.agency = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.productName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.drugClass = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.recallClass = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.emittedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RecallEvent {
    return {
      recallId: isSet(object.recallId)
        ? globalThis.String(object.recallId)
        : isSet(object.recall_id)
        ? globalThis.String(object.recall_id)
        : "",
      agency: isSet(object.agency) ? globalThis.String(object.agency) : "",
      productName: isSet(object.productName)
        ? globalThis.String(object.productName)
        : isSet(object.product_name)
        ? globalThis.String(object.product_name)
        : "",
      drugClass: isSet(object.drugClass)
        ? globalThis.String(object.drugClass)
        : isSet(object.drug_class)
        ? globalThis.String(object.drug_class)
        : "",
      recallClass: isSet(object.recallClass)
        ? globalThis.String(object.recallClass)
        : isSet(object.recall_class)
        ? globalThis.String(object.recall_class)
        : "",
      emittedAt: isSet(object.emittedAt)
        ? fromJsonTimestamp(object.emittedAt)
        : isSet(object.emitted_at)
        ? fromJsonTimestamp(object.emitted_at)
        : undefined,
    };
  },

  toJSON(message: RecallEvent): unknown {
    const obj: any = {};
    if (message.recallId !== "") {
      obj.recallId = message.recallId;
    }
    if (message.agency !== "") {
      obj.agency = message.agency;
    }
    if (message.productName !== "") {
      obj.productName = message.productName;
    }
    if (message.drugClass !== "") {
      obj.drugClass = message.drugClass;
    }
    if (message.recallClass !== "") {
      obj.recallClass = message.recallClass;
    }
    if (message.emittedAt !== undefined) {
      obj.emittedAt = message.emittedAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<RecallEvent>): RecallEvent {
    return RecallEvent.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RecallEvent>): RecallEvent {
    const message = createBaseRecallEvent();
    message.recallId = object.recallId ?? "";
    message.agency = object.agency ?? "";
    message.productName = object.productName ?? "";
    message.drugClass = object.drugClass ?? "";
    message.recallClass = object.recallClass ?? "";
    message.emittedAt = object.emittedAt ?? undefined;
    return message;
  },
};

function createBaseClickEvent(): ClickEvent {
  return { sessionId: "", queryId: "", clickedDocId: "", clickedPosition: 0, variant: "", at: undefined };
}

export const ClickEvent: MessageFns<ClickEvent> = {
  encode(message: ClickEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.queryId !== "") {
      writer.uint32(18).string(message.queryId);
    }
    if (message.clickedDocId !== "") {
      writer.uint32(26).string(message.clickedDocId);
    }
    if (message.clickedPosition !== 0) {
      writer.uint32(32).int32(message.clickedPosition);
    }
    if (message.variant !== "") {
      writer.uint32(42).string(message.variant);
    }
    if (message.at !== undefined) {
      Timestamp.encode(toTimestamp(message.at), writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClickEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClickEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.queryId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.clickedDocId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.clickedPosition = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.variant = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.at = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClickEvent {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      queryId: isSet(object.queryId)
        ? globalThis.String(object.queryId)
        : isSet(object.query_id)
        ? globalThis.String(object.query_id)
        : "",
      clickedDocId: isSet(object.clickedDocId)
        ? globalThis.String(object.clickedDocId)
        : isSet(object.clicked_doc_id)
        ? globalThis.String(object.clicked_doc_id)
        : "",
      clickedPosition: isSet(object.clickedPosition)
        ? globalThis.Number(object.clickedPosition)
        : isSet(object.clicked_position)
        ? globalThis.Number(object.clicked_position)
        : 0,
      variant: isSet(object.variant) ? globalThis.String(object.variant) : "",
      at: isSet(object.at) ? fromJsonTimestamp(object.at) : undefined,
    };
  },

  toJSON(message: ClickEvent): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.queryId !== "") {
      obj.queryId = message.queryId;
    }
    if (message.clickedDocId !== "") {
      obj.clickedDocId = message.clickedDocId;
    }
    if (message.clickedPosition !== 0) {
      obj.clickedPosition = Math.round(message.clickedPosition);
    }
    if (message.variant !== "") {
      obj.variant = message.variant;
    }
    if (message.at !== undefined) {
      obj.at = message.at.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<ClickEvent>): ClickEvent {
    return ClickEvent.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ClickEvent>): ClickEvent {
    const message = createBaseClickEvent();
    message.sessionId = object.sessionId ?? "";
    message.queryId = object.queryId ?? "";
    message.clickedDocId = object.clickedDocId ?? "";
    message.clickedPosition = object.clickedPosition ?? 0;
    message.variant = object.variant ?? "";
    message.at = object.at ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
