// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: evidencelens/v1/scorer.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Timestamp } from "../../google/protobuf/timestamp";
import { Document, StudyType, studyTypeFromJSON, studyTypeToJSON } from "./document";

export const protobufPackage = "evidencelens.v1";

export interface SearchRequest {
  /**
   * Free-text query. Synonyms expansion happens server-side
   * (config/synonyms.json) so the client passes raw user input.
   */
  query: string;
  /** Optional facet / range filters. All filters AND together. */
  filters:
    | SearchFilters
    | undefined;
  /** Maximum results to return across all waves. Default 50, max 200. */
  topK: number;
  /**
   * A/B variant assignment from Firestore lookup, used as a feature for
   * experiment-gated scoring tweaks (e.g. recency_half_life experiment).
   * Empty when no experiment is active. See spec §11.
   */
  variant: string;
  /**
   * Anonymous session id. Used only for click attribution; never logged
   * into BYOK telemetry, never tied to PII.
   */
  sessionId: string;
}

export interface SearchFilters {
  studyTypes: StudyType[];
  /** Inclusive year range. Zero values mean "no bound". */
  publishedYearMin: number;
  publishedYearMax: number;
  meshTerms: string[];
  /** e.g. ["pubmed", "ctgov"] */
  sources: string[];
  /** e.g. ["CC-BY-4.0"] */
  licenses: string[];
  /**
   * If true, only include documents whose authors have at least one
   * matched Open Payments record. Used by COI-aware queries.
   */
  onlyWithCoi: boolean;
  /** If true, only include documents with stored full text. */
  onlyWithFullText: boolean;
  /** If true, exclude journals flagged as predatory by Beall's list. */
  excludePredatoryJournals: boolean;
}

/**
 * Streamed back from the scorer in waves. Each message includes the cursor
 * metadata so the client can know whether more is coming.
 */
export interface PartialResults {
  results: ScoredResult[];
  /**
   * Monotonically increasing across waves of a single request. First wave
   * is 1.
   */
  wave: number;
  /**
   * True on the final message of a stream. Lets the client commit final
   * analytics events.
   */
  isFinal: boolean;
  /**
   * Wall-clock latency from request start to this wave being sent. Used
   * by the gateway to populate the WebSocket message and by Grafana for
   * wave-latency histograms.
   */
  elapsedMs: number;
}

/**
 * One scored search result. The full Document is included so the gateway
 * does not need a follow-up fetch for the result list view; the document
 * drawer fetches additional fields (full_text, citation neighborhood) on
 * demand via DocumentService.
 */
export interface ScoredResult {
  document:
    | Document
    | undefined;
  /**
   * Final fused + LTR-reranked score. Higher is better. Not normalized to
   * any fixed range; only meaningful for ordering within a single response.
   */
  finalScore: number;
  /**
   * Sub-scores for explainability and debugging. Consumed by the
   * frontend's "why this result?" affordance and by LTR retraining.
   */
  breakdown: ScoreBreakdown | undefined;
}

export interface ScoreBreakdown {
  bm25Score: number;
  vectorScore: number;
  citationPagerank: number;
  recencyScore: number;
  rrfScore: number;
  ltrScore: number;
  /** e.g. "ltr_v3" */
  ltrModelVersion: string;
}

export interface ScorerHealthzRequest {
}

export interface ScorerHealthzResponse {
  /**
   * "ok" | "degraded" | "down". "degraded" means at least one sub-scorer
   * is offline but the service can still serve queries with reduced
   * recall (e.g. citation scorer down because Neo4j is rebuilding).
   */
  status: string;
  degradedComponents: string[];
  checkedAt: Date | undefined;
}

function createBaseSearchRequest(): SearchRequest {
  return { query: "", filters: undefined, topK: 0, variant: "", sessionId: "" };
}

export const SearchRequest: MessageFns<SearchRequest> = {
  encode(message: SearchRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== "") {
      writer.uint32(10).string(message.query);
    }
    if (message.filters !== undefined) {
      SearchFilters.encode(message.filters, writer.uint32(18).fork()).join();
    }
    if (message.topK !== 0) {
      writer.uint32(24).int32(message.topK);
    }
    if (message.variant !== "") {
      writer.uint32(34).string(message.variant);
    }
    if (message.sessionId !== "") {
      writer.uint32(42).string(message.sessionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filters = SearchFilters.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.topK = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.variant = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchRequest {
    return {
      query: isSet(object.query) ? globalThis.String(object.query) : "",
      filters: isSet(object.filters) ? SearchFilters.fromJSON(object.filters) : undefined,
      topK: isSet(object.topK)
        ? globalThis.Number(object.topK)
        : isSet(object.top_k)
        ? globalThis.Number(object.top_k)
        : 0,
      variant: isSet(object.variant) ? globalThis.String(object.variant) : "",
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
    };
  },

  toJSON(message: SearchRequest): unknown {
    const obj: any = {};
    if (message.query !== "") {
      obj.query = message.query;
    }
    if (message.filters !== undefined) {
      obj.filters = SearchFilters.toJSON(message.filters);
    }
    if (message.topK !== 0) {
      obj.topK = Math.round(message.topK);
    }
    if (message.variant !== "") {
      obj.variant = message.variant;
    }
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    return obj;
  },

  create(base?: DeepPartial<SearchRequest>): SearchRequest {
    return SearchRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SearchRequest>): SearchRequest {
    const message = createBaseSearchRequest();
    message.query = object.query ?? "";
    message.filters = (object.filters !== undefined && object.filters !== null)
      ? SearchFilters.fromPartial(object.filters)
      : undefined;
    message.topK = object.topK ?? 0;
    message.variant = object.variant ?? "";
    message.sessionId = object.sessionId ?? "";
    return message;
  },
};

function createBaseSearchFilters(): SearchFilters {
  return {
    studyTypes: [],
    publishedYearMin: 0,
    publishedYearMax: 0,
    meshTerms: [],
    sources: [],
    licenses: [],
    onlyWithCoi: false,
    onlyWithFullText: false,
    excludePredatoryJournals: false,
  };
}

export const SearchFilters: MessageFns<SearchFilters> = {
  encode(message: SearchFilters, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.studyTypes) {
      writer.int32(v);
    }
    writer.join();
    if (message.publishedYearMin !== 0) {
      writer.uint32(16).int32(message.publishedYearMin);
    }
    if (message.publishedYearMax !== 0) {
      writer.uint32(24).int32(message.publishedYearMax);
    }
    for (const v of message.meshTerms) {
      writer.uint32(34).string(v!);
    }
    for (const v of message.sources) {
      writer.uint32(42).string(v!);
    }
    for (const v of message.licenses) {
      writer.uint32(50).string(v!);
    }
    if (message.onlyWithCoi !== false) {
      writer.uint32(56).bool(message.onlyWithCoi);
    }
    if (message.onlyWithFullText !== false) {
      writer.uint32(64).bool(message.onlyWithFullText);
    }
    if (message.excludePredatoryJournals !== false) {
      writer.uint32(72).bool(message.excludePredatoryJournals);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchFilters {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchFilters();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.studyTypes.push(reader.int32() as any);

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.studyTypes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.publishedYearMin = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.publishedYearMax = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.meshTerms.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sources.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.licenses.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.onlyWithCoi = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.onlyWithFullText = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.excludePredatoryJournals = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchFilters {
    return {
      studyTypes: globalThis.Array.isArray(object?.studyTypes)
        ? object.studyTypes.map((e: any) => studyTypeFromJSON(e))
        : globalThis.Array.isArray(object?.study_types)
        ? object.study_types.map((e: any) => studyTypeFromJSON(e))
        : [],
      publishedYearMin: isSet(object.publishedYearMin)
        ? globalThis.Number(object.publishedYearMin)
        : isSet(object.published_year_min)
        ? globalThis.Number(object.published_year_min)
        : 0,
      publishedYearMax: isSet(object.publishedYearMax)
        ? globalThis.Number(object.publishedYearMax)
        : isSet(object.published_year_max)
        ? globalThis.Number(object.published_year_max)
        : 0,
      meshTerms: globalThis.Array.isArray(object?.meshTerms)
        ? object.meshTerms.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.mesh_terms)
        ? object.mesh_terms.map((e: any) => globalThis.String(e))
        : [],
      sources: globalThis.Array.isArray(object?.sources)
        ? object.sources.map((e: any) => globalThis.String(e))
        : [],
      licenses: globalThis.Array.isArray(object?.licenses) ? object.licenses.map((e: any) => globalThis.String(e)) : [],
      onlyWithCoi: isSet(object.onlyWithCoi)
        ? globalThis.Boolean(object.onlyWithCoi)
        : isSet(object.only_with_coi)
        ? globalThis.Boolean(object.only_with_coi)
        : false,
      onlyWithFullText: isSet(object.onlyWithFullText)
        ? globalThis.Boolean(object.onlyWithFullText)
        : isSet(object.only_with_full_text)
        ? globalThis.Boolean(object.only_with_full_text)
        : false,
      excludePredatoryJournals: isSet(object.excludePredatoryJournals)
        ? globalThis.Boolean(object.excludePredatoryJournals)
        : isSet(object.exclude_predatory_journals)
        ? globalThis.Boolean(object.exclude_predatory_journals)
        : false,
    };
  },

  toJSON(message: SearchFilters): unknown {
    const obj: any = {};
    if (message.studyTypes?.length) {
      obj.studyTypes = message.studyTypes.map((e) => studyTypeToJSON(e));
    }
    if (message.publishedYearMin !== 0) {
      obj.publishedYearMin = Math.round(message.publishedYearMin);
    }
    if (message.publishedYearMax !== 0) {
      obj.publishedYearMax = Math.round(message.publishedYearMax);
    }
    if (message.meshTerms?.length) {
      obj.meshTerms = message.meshTerms;
    }
    if (message.sources?.length) {
      obj.sources = message.sources;
    }
    if (message.licenses?.length) {
      obj.licenses = message.licenses;
    }
    if (message.onlyWithCoi !== false) {
      obj.onlyWithCoi = message.onlyWithCoi;
    }
    if (message.onlyWithFullText !== false) {
      obj.onlyWithFullText = message.onlyWithFullText;
    }
    if (message.excludePredatoryJournals !== false) {
      obj.excludePredatoryJournals = message.excludePredatoryJournals;
    }
    return obj;
  },

  create(base?: DeepPartial<SearchFilters>): SearchFilters {
    return SearchFilters.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SearchFilters>): SearchFilters {
    const message = createBaseSearchFilters();
    message.studyTypes = object.studyTypes?.map((e) => e) || [];
    message.publishedYearMin = object.publishedYearMin ?? 0;
    message.publishedYearMax = object.publishedYearMax ?? 0;
    message.meshTerms = object.meshTerms?.map((e) => e) || [];
    message.sources = object.sources?.map((e) => e) || [];
    message.licenses = object.licenses?.map((e) => e) || [];
    message.onlyWithCoi = object.onlyWithCoi ?? false;
    message.onlyWithFullText = object.onlyWithFullText ?? false;
    message.excludePredatoryJournals = object.excludePredatoryJournals ?? false;
    return message;
  },
};

function createBasePartialResults(): PartialResults {
  return { results: [], wave: 0, isFinal: false, elapsedMs: 0 };
}

export const PartialResults: MessageFns<PartialResults> = {
  encode(message: PartialResults, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.results) {
      ScoredResult.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.wave !== 0) {
      writer.uint32(16).int32(message.wave);
    }
    if (message.isFinal !== false) {
      writer.uint32(24).bool(message.isFinal);
    }
    if (message.elapsedMs !== 0) {
      writer.uint32(32).int64(message.elapsedMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PartialResults {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePartialResults();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.results.push(ScoredResult.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.wave = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isFinal = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.elapsedMs = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PartialResults {
    return {
      results: globalThis.Array.isArray(object?.results)
        ? object.results.map((e: any) => ScoredResult.fromJSON(e))
        : [],
      wave: isSet(object.wave) ? globalThis.Number(object.wave) : 0,
      isFinal: isSet(object.isFinal)
        ? globalThis.Boolean(object.isFinal)
        : isSet(object.is_final)
        ? globalThis.Boolean(object.is_final)
        : false,
      elapsedMs: isSet(object.elapsedMs)
        ? globalThis.Number(object.elapsedMs)
        : isSet(object.elapsed_ms)
        ? globalThis.Number(object.elapsed_ms)
        : 0,
    };
  },

  toJSON(message: PartialResults): unknown {
    const obj: any = {};
    if (message.results?.length) {
      obj.results = message.results.map((e) => ScoredResult.toJSON(e));
    }
    if (message.wave !== 0) {
      obj.wave = Math.round(message.wave);
    }
    if (message.isFinal !== false) {
      obj.isFinal = message.isFinal;
    }
    if (message.elapsedMs !== 0) {
      obj.elapsedMs = Math.round(message.elapsedMs);
    }
    return obj;
  },

  create(base?: DeepPartial<PartialResults>): PartialResults {
    return PartialResults.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PartialResults>): PartialResults {
    const message = createBasePartialResults();
    message.results = object.results?.map((e) => ScoredResult.fromPartial(e)) || [];
    message.wave = object.wave ?? 0;
    message.isFinal = object.isFinal ?? false;
    message.elapsedMs = object.elapsedMs ?? 0;
    return message;
  },
};

function createBaseScoredResult(): ScoredResult {
  return { document: undefined, finalScore: 0, breakdown: undefined };
}

export const ScoredResult: MessageFns<ScoredResult> = {
  encode(message: ScoredResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.document !== undefined) {
      Document.encode(message.document, writer.uint32(10).fork()).join();
    }
    if (message.finalScore !== 0) {
      writer.uint32(17).double(message.finalScore);
    }
    if (message.breakdown !== undefined) {
      ScoreBreakdown.encode(message.breakdown, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScoredResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScoredResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.document = Document.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.finalScore = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.breakdown = ScoreBreakdown.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScoredResult {
    return {
      document: isSet(object.document) ? Document.fromJSON(object.document) : undefined,
      finalScore: isSet(object.finalScore)
        ? globalThis.Number(object.finalScore)
        : isSet(object.final_score)
        ? globalThis.Number(object.final_score)
        : 0,
      breakdown: isSet(object.breakdown) ? ScoreBreakdown.fromJSON(object.breakdown) : undefined,
    };
  },

  toJSON(message: ScoredResult): unknown {
    const obj: any = {};
    if (message.document !== undefined) {
      obj.document = Document.toJSON(message.document);
    }
    if (message.finalScore !== 0) {
      obj.finalScore = message.finalScore;
    }
    if (message.breakdown !== undefined) {
      obj.breakdown = ScoreBreakdown.toJSON(message.breakdown);
    }
    return obj;
  },

  create(base?: DeepPartial<ScoredResult>): ScoredResult {
    return ScoredResult.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ScoredResult>): ScoredResult {
    const message = createBaseScoredResult();
    message.document = (object.document !== undefined && object.document !== null)
      ? Document.fromPartial(object.document)
      : undefined;
    message.finalScore = object.finalScore ?? 0;
    message.breakdown = (object.breakdown !== undefined && object.breakdown !== null)
      ? ScoreBreakdown.fromPartial(object.breakdown)
      : undefined;
    return message;
  },
};

function createBaseScoreBreakdown(): ScoreBreakdown {
  return {
    bm25Score: 0,
    vectorScore: 0,
    citationPagerank: 0,
    recencyScore: 0,
    rrfScore: 0,
    ltrScore: 0,
    ltrModelVersion: "",
  };
}

export const ScoreBreakdown: MessageFns<ScoreBreakdown> = {
  encode(message: ScoreBreakdown, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bm25Score !== 0) {
      writer.uint32(9).double(message.bm25Score);
    }
    if (message.vectorScore !== 0) {
      writer.uint32(17).double(message.vectorScore);
    }
    if (message.citationPagerank !== 0) {
      writer.uint32(25).double(message.citationPagerank);
    }
    if (message.recencyScore !== 0) {
      writer.uint32(33).double(message.recencyScore);
    }
    if (message.rrfScore !== 0) {
      writer.uint32(41).double(message.rrfScore);
    }
    if (message.ltrScore !== 0) {
      writer.uint32(49).double(message.ltrScore);
    }
    if (message.ltrModelVersion !== "") {
      writer.uint32(58).string(message.ltrModelVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScoreBreakdown {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScoreBreakdown();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.bm25Score = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.vectorScore = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.citationPagerank = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.recencyScore = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.rrfScore = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.ltrScore = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.ltrModelVersion = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScoreBreakdown {
    return {
      bm25Score: isSet(object.bm25Score)
        ? globalThis.Number(object.bm25Score)
        : isSet(object.bm25_score)
        ? globalThis.Number(object.bm25_score)
        : 0,
      vectorScore: isSet(object.vectorScore)
        ? globalThis.Number(object.vectorScore)
        : isSet(object.vector_score)
        ? globalThis.Number(object.vector_score)
        : 0,
      citationPagerank: isSet(object.citationPagerank)
        ? globalThis.Number(object.citationPagerank)
        : isSet(object.citation_pagerank)
        ? globalThis.Number(object.citation_pagerank)
        : 0,
      recencyScore: isSet(object.recencyScore)
        ? globalThis.Number(object.recencyScore)
        : isSet(object.recency_score)
        ? globalThis.Number(object.recency_score)
        : 0,
      rrfScore: isSet(object.rrfScore)
        ? globalThis.Number(object.rrfScore)
        : isSet(object.rrf_score)
        ? globalThis.Number(object.rrf_score)
        : 0,
      ltrScore: isSet(object.ltrScore)
        ? globalThis.Number(object.ltrScore)
        : isSet(object.ltr_score)
        ? globalThis.Number(object.ltr_score)
        : 0,
      ltrModelVersion: isSet(object.ltrModelVersion)
        ? globalThis.String(object.ltrModelVersion)
        : isSet(object.ltr_model_version)
        ? globalThis.String(object.ltr_model_version)
        : "",
    };
  },

  toJSON(message: ScoreBreakdown): unknown {
    const obj: any = {};
    if (message.bm25Score !== 0) {
      obj.bm25Score = message.bm25Score;
    }
    if (message.vectorScore !== 0) {
      obj.vectorScore = message.vectorScore;
    }
    if (message.citationPagerank !== 0) {
      obj.citationPagerank = message.citationPagerank;
    }
    if (message.recencyScore !== 0) {
      obj.recencyScore = message.recencyScore;
    }
    if (message.rrfScore !== 0) {
      obj.rrfScore = message.rrfScore;
    }
    if (message.ltrScore !== 0) {
      obj.ltrScore = message.ltrScore;
    }
    if (message.ltrModelVersion !== "") {
      obj.ltrModelVersion = message.ltrModelVersion;
    }
    return obj;
  },

  create(base?: DeepPartial<ScoreBreakdown>): ScoreBreakdown {
    return ScoreBreakdown.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ScoreBreakdown>): ScoreBreakdown {
    const message = createBaseScoreBreakdown();
    message.bm25Score = object.bm25Score ?? 0;
    message.vectorScore = object.vectorScore ?? 0;
    message.citationPagerank = object.citationPagerank ?? 0;
    message.recencyScore = object.recencyScore ?? 0;
    message.rrfScore = object.rrfScore ?? 0;
    message.ltrScore = object.ltrScore ?? 0;
    message.ltrModelVersion = object.ltrModelVersion ?? "";
    return message;
  },
};

function createBaseScorerHealthzRequest(): ScorerHealthzRequest {
  return {};
}

export const ScorerHealthzRequest: MessageFns<ScorerHealthzRequest> = {
  encode(_: ScorerHealthzRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScorerHealthzRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScorerHealthzRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ScorerHealthzRequest {
    return {};
  },

  toJSON(_: ScorerHealthzRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<ScorerHealthzRequest>): ScorerHealthzRequest {
    return ScorerHealthzRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ScorerHealthzRequest>): ScorerHealthzRequest {
    const message = createBaseScorerHealthzRequest();
    return message;
  },
};

function createBaseScorerHealthzResponse(): ScorerHealthzResponse {
  return { status: "", degradedComponents: [], checkedAt: undefined };
}

export const ScorerHealthzResponse: MessageFns<ScorerHealthzResponse> = {
  encode(message: ScorerHealthzResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    for (const v of message.degradedComponents) {
      writer.uint32(18).string(v!);
    }
    if (message.checkedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.checkedAt), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScorerHealthzResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScorerHealthzResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.degradedComponents.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.checkedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScorerHealthzResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      degradedComponents: globalThis.Array.isArray(object?.degradedComponents)
        ? object.degradedComponents.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.degraded_components)
        ? object.degraded_components.map((e: any) => globalThis.String(e))
        : [],
      checkedAt: isSet(object.checkedAt)
        ? fromJsonTimestamp(object.checkedAt)
        : isSet(object.checked_at)
        ? fromJsonTimestamp(object.checked_at)
        : undefined,
    };
  },

  toJSON(message: ScorerHealthzResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.degradedComponents?.length) {
      obj.degradedComponents = message.degradedComponents;
    }
    if (message.checkedAt !== undefined) {
      obj.checkedAt = message.checkedAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<ScorerHealthzResponse>): ScorerHealthzResponse {
    return ScorerHealthzResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ScorerHealthzResponse>): ScorerHealthzResponse {
    const message = createBaseScorerHealthzResponse();
    message.status = object.status ?? "";
    message.degradedComponents = object.degradedComponents?.map((e) => e) || [];
    message.checkedAt = object.checkedAt ?? undefined;
    return message;
  },
};

export type ScorerServiceService = typeof ScorerServiceService;
export const ScorerServiceService = {
  /**
   * Server-streaming search. The server emits multiple PartialResults
   * messages over the lifetime of a single request, each refining the
   * ranking with more sub-scorer signals. Clients should render each wave
   * immediately and replace prior content.
   *
   * Deadline propagation: the gateway sets `grpc-timeout` (e.g. 800m).
   * The scorer subdivides budget across sub-scorers and emits whatever it
   * has when the deadline expires.
   */
  search: {
    path: "/evidencelens.v1.ScorerService/Search" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: SearchRequest): Buffer => Buffer.from(SearchRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SearchRequest => SearchRequest.decode(value),
    responseSerialize: (value: PartialResults): Buffer => Buffer.from(PartialResults.encode(value).finish()),
    responseDeserialize: (value: Buffer): PartialResults => PartialResults.decode(value),
  },
  /** Synchronous health probe used by docker-compose / Kubernetes / OTel. */
  healthz: {
    path: "/evidencelens.v1.ScorerService/Healthz" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ScorerHealthzRequest): Buffer => Buffer.from(ScorerHealthzRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ScorerHealthzRequest => ScorerHealthzRequest.decode(value),
    responseSerialize: (value: ScorerHealthzResponse): Buffer =>
      Buffer.from(ScorerHealthzResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ScorerHealthzResponse => ScorerHealthzResponse.decode(value),
  },
} as const;

export interface ScorerServiceServer extends UntypedServiceImplementation {
  /**
   * Server-streaming search. The server emits multiple PartialResults
   * messages over the lifetime of a single request, each refining the
   * ranking with more sub-scorer signals. Clients should render each wave
   * immediately and replace prior content.
   *
   * Deadline propagation: the gateway sets `grpc-timeout` (e.g. 800m).
   * The scorer subdivides budget across sub-scorers and emits whatever it
   * has when the deadline expires.
   */
  search: handleServerStreamingCall<SearchRequest, PartialResults>;
  /** Synchronous health probe used by docker-compose / Kubernetes / OTel. */
  healthz: handleUnaryCall<ScorerHealthzRequest, ScorerHealthzResponse>;
}

export interface ScorerServiceClient extends Client {
  /**
   * Server-streaming search. The server emits multiple PartialResults
   * messages over the lifetime of a single request, each refining the
   * ranking with more sub-scorer signals. Clients should render each wave
   * immediately and replace prior content.
   *
   * Deadline propagation: the gateway sets `grpc-timeout` (e.g. 800m).
   * The scorer subdivides budget across sub-scorers and emits whatever it
   * has when the deadline expires.
   */
  search(request: SearchRequest, options?: Partial<CallOptions>): ClientReadableStream<PartialResults>;
  search(
    request: SearchRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<PartialResults>;
  /** Synchronous health probe used by docker-compose / Kubernetes / OTel. */
  healthz(
    request: ScorerHealthzRequest,
    callback: (error: ServiceError | null, response: ScorerHealthzResponse) => void,
  ): ClientUnaryCall;
  healthz(
    request: ScorerHealthzRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ScorerHealthzResponse) => void,
  ): ClientUnaryCall;
  healthz(
    request: ScorerHealthzRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ScorerHealthzResponse) => void,
  ): ClientUnaryCall;
}

export const ScorerServiceClient = makeGenericClientConstructor(
  ScorerServiceService,
  "evidencelens.v1.ScorerService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ScorerServiceClient;
  service: typeof ScorerServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
