# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from evidencelens.v1 import embedder_pb2 as evidencelens_dot_v1_dot_embedder__pb2


class EmbedderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.stream_stream(
                '/evidencelens.v1.EmbedderService/Embed',
                request_serializer=evidencelens_dot_v1_dot_embedder__pb2.EmbedRequest.SerializeToString,
                response_deserializer=evidencelens_dot_v1_dot_embedder__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.EmbedOnce = channel.unary_unary(
                '/evidencelens.v1.EmbedderService/EmbedOnce',
                request_serializer=evidencelens_dot_v1_dot_embedder__pb2.EmbedRequest.SerializeToString,
                response_deserializer=evidencelens_dot_v1_dot_embedder__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.Healthz = channel.unary_unary(
                '/evidencelens.v1.EmbedderService/Healthz',
                request_serializer=evidencelens_dot_v1_dot_embedder__pb2.EmbedderHealthzRequest.SerializeToString,
                response_deserializer=evidencelens_dot_v1_dot_embedder__pb2.EmbedderHealthzResponse.FromString,
                _registered_method=True)


class EmbedderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Embed(self, request_iterator, context):
        """Bidirectional streaming embedding. The server batches incoming
        requests dynamically (batch=32, max-wait=25ms) for GPU throughput.
        Responses are emitted in arrival order; clients should match by
        request_id rather than position.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedOnce(self, request, context):
        """Single-shot variant for callers that don't want to manage a stream
        (e.g. one-off CLI tools, tests). Internally rate-limited to avoid
        starving the streaming queue.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Healthz(self, request, context):
        """Health probe. Returns "degraded" when running on the CPU fallback
        (BGE-small-en-v1.5, 384-d) instead of GPU BGE-M3 (1024-d). Consumers
        should validate `embedding_model` on every response, not just at
        startup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbedderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embed': grpc.stream_stream_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=evidencelens_dot_v1_dot_embedder__pb2.EmbedRequest.FromString,
                    response_serializer=evidencelens_dot_v1_dot_embedder__pb2.EmbedResponse.SerializeToString,
            ),
            'EmbedOnce': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedOnce,
                    request_deserializer=evidencelens_dot_v1_dot_embedder__pb2.EmbedRequest.FromString,
                    response_serializer=evidencelens_dot_v1_dot_embedder__pb2.EmbedResponse.SerializeToString,
            ),
            'Healthz': grpc.unary_unary_rpc_method_handler(
                    servicer.Healthz,
                    request_deserializer=evidencelens_dot_v1_dot_embedder__pb2.EmbedderHealthzRequest.FromString,
                    response_serializer=evidencelens_dot_v1_dot_embedder__pb2.EmbedderHealthzResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evidencelens.v1.EmbedderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('evidencelens.v1.EmbedderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbedderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Embed(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/evidencelens.v1.EmbedderService/Embed',
            evidencelens_dot_v1_dot_embedder__pb2.EmbedRequest.SerializeToString,
            evidencelens_dot_v1_dot_embedder__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedOnce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evidencelens.v1.EmbedderService/EmbedOnce',
            evidencelens_dot_v1_dot_embedder__pb2.EmbedRequest.SerializeToString,
            evidencelens_dot_v1_dot_embedder__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Healthz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evidencelens.v1.EmbedderService/Healthz',
            evidencelens_dot_v1_dot_embedder__pb2.EmbedderHealthzRequest.SerializeToString,
            evidencelens_dot_v1_dot_embedder__pb2.EmbedderHealthzResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
