# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: evidencelens/v1/embedder.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'evidencelens/v1/embedder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x65videncelens/v1/embedder.proto\x12\x0f\x65videncelens.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n\x0c\x45mbedRequest\x12\x1d\n\nrequest_id\x18\x01 \x01(\tR\trequestId\x12\x14\n\x05texts\x18\x02 \x03(\tR\x05texts\"\x99\x01\n\rEmbedResponse\x12\x1d\n\nrequest_id\x18\x01 \x01(\tR\trequestId\x12@\n\nembeddings\x18\x02 \x03(\x0b\x32 .evidencelens.v1.EmbeddingVectorR\nembeddings\x12\'\n\x0f\x65mbedding_model\x18\x03 \x01(\tR\x0e\x65mbeddingModel\";\n\x0f\x45mbeddingVector\x12\x16\n\x06values\x18\x01 \x03(\x02R\x06values\x12\x10\n\x03\x64im\x18\x02 \x01(\x05R\x03\x64im\"\x18\n\x16\x45mbedderHealthzRequest\"\xad\x01\n\x17\x45mbedderHealthzResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\x12\'\n\x0f\x65mbedding_model\x18\x02 \x01(\tR\x0e\x65mbeddingModel\x12\x16\n\x06\x64\x65tail\x18\x03 \x01(\tR\x06\x64\x65tail\x12\x39\n\nchecked_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcheckedAt2\x87\x02\n\x0f\x45mbedderService\x12J\n\x05\x45mbed\x12\x1d.evidencelens.v1.EmbedRequest\x1a\x1e.evidencelens.v1.EmbedResponse(\x01\x30\x01\x12J\n\tEmbedOnce\x12\x1d.evidencelens.v1.EmbedRequest\x1a\x1e.evidencelens.v1.EmbedResponse\x12\\\n\x07Healthz\x12\'.evidencelens.v1.EmbedderHealthzRequest\x1a(.evidencelens.v1.EmbedderHealthzResponseB\xd3\x01\n\x13\x63om.evidencelens.v1B\rEmbedderProtoP\x01ZPgithub.com/evidencelens/evidencelens/proto/gen/go/evidencelens/v1;evidencelensv1\xa2\x02\x03\x45XX\xaa\x02\x0f\x45videncelens.V1\xca\x02\x0f\x45videncelens\\V1\xe2\x02\x1b\x45videncelens\\V1\\GPBMetadata\xea\x02\x10\x45videncelens::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'evidencelens.v1.embedder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.evidencelens.v1B\rEmbedderProtoP\001ZPgithub.com/evidencelens/evidencelens/proto/gen/go/evidencelens/v1;evidencelensv1\242\002\003EXX\252\002\017Evidencelens.V1\312\002\017Evidencelens\\V1\342\002\033Evidencelens\\V1\\GPBMetadata\352\002\020Evidencelens::V1'
  _globals['_EMBEDREQUEST']._serialized_start=84
  _globals['_EMBEDREQUEST']._serialized_end=151
  _globals['_EMBEDRESPONSE']._serialized_start=154
  _globals['_EMBEDRESPONSE']._serialized_end=307
  _globals['_EMBEDDINGVECTOR']._serialized_start=309
  _globals['_EMBEDDINGVECTOR']._serialized_end=368
  _globals['_EMBEDDERHEALTHZREQUEST']._serialized_start=370
  _globals['_EMBEDDERHEALTHZREQUEST']._serialized_end=394
  _globals['_EMBEDDERHEALTHZRESPONSE']._serialized_start=397
  _globals['_EMBEDDERHEALTHZRESPONSE']._serialized_end=570
  _globals['_EMBEDDERSERVICE']._serialized_start=573
  _globals['_EMBEDDERSERVICE']._serialized_end=836
# @@protoc_insertion_point(module_scope)
