# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: evidencelens/v1/events.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'evidencelens/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evidencelens.v1 import document_pb2 as evidencelens_dot_v1_dot_document__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65videncelens/v1/events.proto\x12\x0f\x65videncelens.v1\x1a\x1e\x65videncelens/v1/document.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x01\n\x0bRawDocEvent\x12\x16\n\x06source\x18\x01 \x01(\tR\x06source\x12\x15\n\x06\x64oc_id\x18\x02 \x01(\tR\x05\x64ocId\x12\x1d\n\nobject_key\x18\x03 \x01(\tR\tobjectKey\x12;\n\x0bingested_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\ningestedAt\"\x89\x01\n\x11IndexableDocEvent\x12\x35\n\x08\x64ocument\x18\x01 \x01(\x0b\x32\x19.evidencelens.v1.DocumentR\x08\x64ocument\x12=\n\x0cprocessed_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0bprocessedAt\"\xe2\x01\n\x0bRecallEvent\x12\x1b\n\trecall_id\x18\x01 \x01(\tR\x08recallId\x12\x16\n\x06\x61gency\x18\x02 \x01(\tR\x06\x61gency\x12!\n\x0cproduct_name\x18\x03 \x01(\tR\x0bproductName\x12\x1d\n\ndrug_class\x18\x04 \x01(\tR\tdrugClass\x12!\n\x0crecall_class\x18\x05 \x01(\tR\x0brecallClass\x12\x39\n\nemitted_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\temittedAt\"\xdd\x01\n\nClickEvent\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n\x08query_id\x18\x02 \x01(\tR\x07queryId\x12$\n\x0e\x63licked_doc_id\x18\x03 \x01(\tR\x0c\x63lickedDocId\x12)\n\x10\x63licked_position\x18\x04 \x01(\x05R\x0f\x63lickedPosition\x12\x18\n\x07variant\x18\x05 \x01(\tR\x07variant\x12*\n\x02\x61t\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x02\x61tB\xd1\x01\n\x13\x63om.evidencelens.v1B\x0b\x45ventsProtoP\x01ZPgithub.com/evidencelens/evidencelens/proto/gen/go/evidencelens/v1;evidencelensv1\xa2\x02\x03\x45XX\xaa\x02\x0f\x45videncelens.V1\xca\x02\x0f\x45videncelens\\V1\xe2\x02\x1b\x45videncelens\\V1\\GPBMetadata\xea\x02\x10\x45videncelens::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'evidencelens.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.evidencelens.v1B\013EventsProtoP\001ZPgithub.com/evidencelens/evidencelens/proto/gen/go/evidencelens/v1;evidencelensv1\242\002\003EXX\252\002\017Evidencelens.V1\312\002\017Evidencelens\\V1\342\002\033Evidencelens\\V1\\GPBMetadata\352\002\020Evidencelens::V1'
  _globals['_RAWDOCEVENT']._serialized_start=115
  _globals['_RAWDOCEVENT']._serialized_end=267
  _globals['_INDEXABLEDOCEVENT']._serialized_start=270
  _globals['_INDEXABLEDOCEVENT']._serialized_end=407
  _globals['_RECALLEVENT']._serialized_start=410
  _globals['_RECALLEVENT']._serialized_end=636
  _globals['_CLICKEVENT']._serialized_start=639
  _globals['_CLICKEVENT']._serialized_end=860
# @@protoc_insertion_point(module_scope)
